### PR TITLE
Cleaner, Simplified code using C++

### LINKED ISSUE #8: Feature: You are propably going to need a build system
My suggestion is that you should use [cmake](https://cmake.org/) as a build system.
This will make development faster and easier.

### PR DESCRIPTION
**Pull request by xorz57**
- Made a Visual Studio Project
- Splitted up the files
- I just disagree with the active window implementation because it produces "ugly" log information.
- Of course you can re-implement or ask for re-implementation of the code segments that existed before. I hope you find this PR usefull somehow.

Closes #8 #2

### CODE REVIEW

**Comment by xorz57** [comment]
@exler Do you think this is fine?

**Comment by exler** [comment]
@xorz57 I can't look at the code till Saturday evening. Will get to it asap.

**Comment by exler** [comment]
It looks good, but I doesn't output any other character than the {VK_SHIFT} and such. I'm gonna ask you to fix it. Oh, and also I actually really liked the Active Window feature in log file, you don't have to implement it if you want, but I certainly will add it back after I merge your pull request.

**Comment by xorz57** [comment]
@exler ok I will fix it.

**Comment by xorz57** [comment]
@exler Let me know if its ok now :e-mail:

**Comment by exler** [comment]
@xorz57 It's okay now, thanks for your contribution!

**Pull request merged**
